# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '111.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_Window(object):
    def setupUi(self, Main_Window):
        Main_Window.setObjectName("Main_Window")
        Main_Window.resize(839, 619)
        self.Drop_Out_Menu = QtWidgets.QComboBox(Main_Window)
        self.Drop_Out_Menu.setGeometry(QtCore.QRect(170, 130, 461, 71))
        self.Drop_Out_Menu.setToolTipDuration(29)
        self.Drop_Out_Menu.setObjectName("Drop_Out_Menu")
        self.Drop_Out_Menu.addItem("")
        self.Drop_Out_Menu.addItem("")
        self.Mode_Select = QtWidgets.QLabel(Main_Window)
        self.Mode_Select.setGeometry(QtCore.QRect(320, 50, 331, 81))
        self.Mode_Select.setObjectName("Mode_Select")
        self.Clear_Button = QtWidgets.QPushButton(Main_Window)
        self.Clear_Button.setGeometry(QtCore.QRect(20, 360, 191, 61))
        self.Clear_Button.setStyleSheet("")
        self.Clear_Button.setCheckable(False)
        self.Clear_Button.setChecked(False)
        self.Clear_Button.setObjectName("Clear_Button")
        self.MNIST_Random_Draw = QtWidgets.QPushButton(Main_Window)
        self.MNIST_Random_Draw.setGeometry(QtCore.QRect(21, 290, 191, 61))
        self.MNIST_Random_Draw.setCheckable(False)
        self.MNIST_Random_Draw.setObjectName("MNIST_Random_Draw")
        self.Run_Recognize = QtWidgets.QPushButton(Main_Window)
        self.Run_Recognize.setGeometry(QtCore.QRect(20, 430, 191, 71))
        self.Run_Recognize.setStyleSheet("")
        self.Run_Recognize.setObjectName("Run_Recognize")
        self.Image_Show = QtWidgets.QLabel(Main_Window)
        self.Image_Show.setGeometry(QtCore.QRect(540, 300, 224, 224))
        self.Image_Show.setMouseTracking(False)
        self.Image_Show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Image_Show.setFrameShape(QtWidgets.QFrame.Box)
        self.Image_Show.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Image_Show.setLineWidth(4)
        self.Image_Show.setMidLineWidth(0)
        self.Image_Show.setText("")
        self.Image_Show.setObjectName("Image_Show")
        self.Resul_Softmax = QtWidgets.QLabel(Main_Window)
        self.Resul_Softmax.setGeometry(QtCore.QRect(260, 290, 91, 181))
        self.Resul_Softmax.setObjectName("Resul_Softmax")
        self.InputDataSpace = QtWidgets.QLabel(Main_Window)
        self.InputDataSpace.setGeometry(QtCore.QRect(560, 260, 191, 41))
        self.InputDataSpace.setObjectName("InputDataSpace")
        self.verticalLayoutWidget = QtWidgets.QWidget(Main_Window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(540, 300, 221, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.dArea_Layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.dArea_Layout.setContentsMargins(0, 0, 0, 0)
        self.dArea_Layout.setSpacing(0)
        self.dArea_Layout.setObjectName("dArea_Layout")
        self.Predict_Result = QtWidgets.QLabel(Main_Window)
        self.Predict_Result.setGeometry(QtCore.QRect(400, 270, 91, 131))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.Predict_Result.setFont(font)
        self.Predict_Result.setObjectName("Predict_Result")
        self.Softmax_Result = QtWidgets.QLabel(Main_Window)
        self.Softmax_Result.setGeometry(QtCore.QRect(370, 430, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Softmax_Result.setFont(font)
        self.Softmax_Result.setObjectName("Softmax_Result")

        self.retranslateUi(Main_Window)
        self.Drop_Out_Menu.activated['QString'].connect(Main_Window.cbBox_Mode_Callback)
        self.Clear_Button.clicked.connect(Main_Window.pbtClear_Callback)
        self.Run_Recognize.clicked.connect(Main_Window.pbtPredict_Callback)
        self.MNIST_Random_Draw.clicked.connect(Main_Window.pbtGetMnist_Callback)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

    def retranslateUi(self, Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Main_Window.setWindowTitle(_translate("Main_Window", "Digits Recognization"))
        self.Drop_Out_Menu.setItemText(0, _translate("Main_Window", "1: random pick one picture from MNIST test set"))
        self.Drop_Out_Menu.setItemText(1, _translate("Main_Window", "2: draw one digit in the Input Data Space"))
        self.Mode_Select.setText(_translate("Main_Window", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Mode select</span></p></body></html>"))
        self.Clear_Button.setText(_translate("Main_Window", "Clear"))
        self.MNIST_Random_Draw.setText(_translate("Main_Window", "MNIST random draw"))
        self.Run_Recognize.setText(_translate("Main_Window", "Run and Recognize"))
        self.Resul_Softmax.setText(_translate("Main_Window", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Result：</span></p><p><br/></p><p><br/></p><p><span style=\" font-size:12pt; font-weight:600;\">Softmax：</span></p></body></html>"))
        self.InputDataSpace.setText(_translate("Main_Window", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Input Data Space</span></p></body></html>"))
        self.Predict_Result.setText(_translate("Main_Window", "9"))
        self.Softmax_Result.setText(_translate("Main_Window", "0.99999999"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main_Window = QtWidgets.QDialog()
    ui = Ui_Main_Window()
    ui.setupUi(Main_Window)
    Main_Window.show()
    sys.exit(app.exec_())
